name: cine_go
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.20.2
  equatable: ^2.0.5
  # State Management
  flutter_bloc: ^8.1.0

  # Network & API
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  retrofit: ^4.9.0

  # for logging purpose
  logger: ^2.6.0  

  # Navigation & Backend
  go_router: ^17.0.1
  # firebase_core: ^4.3.0
  # firebase_auth: ^6.1.2 # Standard for Firebase apps
  # cloud_firestore: ^6.1.1 # Standard for Firebase apps

  # UI & Animation
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0 # Loading skeleton
  carousel_slider: ^5.0.0 # For movie list slider
  qr_flutter: ^4.1.0
  
  # Configuration & Logic
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  envied: ^1.3.2
  get_it: ^9.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Generation Tools
  build_runner: ^2.6.0
  freezed: ^3.2.3
  json_serializable: ^6.10.0
  retrofit_generator: 10.1.0

  # Utilities
  mockito: ^5.4.5
  flutter_launcher_icons: ^0.14.4
  envied_generator: ^1.3.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/mock_api/
